### ISSUE TITLE
Analysis using a GRCh38 reference

### ISSUE THREAD

**Issue by kalon33** [KCCG/ClinSV#1]
Dear authors,

Is it possible to run a ClinSV analysis using a GRCh38 reference? What are the requirements for this, the steps to follow that are different from the analysis you describe?

Best regards.

**Comment by drmjc** [comment]
Hello,
Andre has recently added support for GRCh38, so please use the refdata-b38_v1.0.tar with ClinSV v1.0, which is available from https://nci.space/_projects/clinsv_b38/

all the best,
Mark

**Comment by kalon33** [comment]
Thanks @drmjc !
