### ISSUE TITLE
Issue with  OS and clinsv 1.0

### ISSUE THREAD

**Issue by IshakYusuf** [KCCG/ClinSV#10]
Dear Developers

Shall I install CentOS 6.8 before install ClinSV to work on build 38?

The operating system  on the server is Ubuntu 18.04.5 lts 

kind wishes

**Comment by MinocheAE** [comment]
ClinSV 0.9 was developed under CentOS 6.8 and ClinSV 1.0 under Centos 8.

So it should be easier to run ClinSV under CentOS.

To verify if ClinSV runs correctly you can compare the QC report of running the provided sample
https://nci.space/_projects/clinsv_b38/NA12878_b38.bam

with the QC report we obtained for it.
https://nci.space/_projects/clinsv_b38/FR05812606.QC_report.pdf

I hope this helps

**Comment by IshakYusuf** [comment]
Thanks for your response
