### ISSUE TITLE
Trouble downloading ClinSV v1.0

### ISSUE THREAD

**Issue by j2moreno** [KCCG/ClinSV#11]
When I try to download ClinSV v1.0 i get this error: 
```
$ wget https://nci.space/_projects/clinsv_b38/ClinSV_scripts_only_v1.0.tar.gz
--2021-08-12 17:57:03--  https://nci.space/_projects/clinsv_b38/ClinSV_scripts_only_v1.0.tar.gz
Resolving nci.space (nci.space)... 130.56.242.205
Connecting to nci.space (nci.space)|130.56.242.205|:443... failed: No route to host.
```

Have the files been moved?

**Comment by drmjc** [comment]
Thanks for reporting this, i can confirm the link does appear to be dead. I'll followup with the sys admins at nci.space.

**Comment by drmjc** [comment]
Hi, the link is working again & thanks for raising the issue.

**Comment by drmjc** [comment]
@MinocheAE please close ticket.
