### ISSUE TITLE
clinsv reference and test data are not available

### ISSUE THREAD

**Issue by tstokowy** [KCCG/ClinSV#12]
Hi, I tried to download and test your package, however the resources are not available.
wget https://nci.space/clinsv/refdata-b37_v0.9.tar

Tomasz Stokowy
Department of Clinical Science
University of Bergen, Norway

**Comment by MinocheAE** [comment]
Thank you for letting us now, we are working on bringing the server back online. I will let you know when it is back

**Comment by shyamrav** [comment]
Hi Andre,

Does this affect the following link as well: https://nci.space/_projects/clinsv_b38/

**Comment by drmjc** [comment]
yes it does & we're still working on getting the server working.

Here are some interim links to download b38 data (valid for 1 month from today):

https://dl.as2.dnanex.us/F/D/VBP2qgvVB52qb8PkKfKqfKF8bY9JVPvvB8yQz265/ClinSV_scripts_only_v1.0.tar.gz
https://dl.as2.dnanex.us/F/D/X7G7Vj2ZPz99972qQZZB443F1p2VGgGzz8qbfVJ9/ClinSV_scripts_only_v1.0.tar.gz.md5sum
https://dl.as2.dnanex.us/F/D/8jy277GF6yyv19VBxKZ6J1YpjZ1Zb0z3P3xKJx4F/ClinSV_x86_64_v1.0.tar.gz
https://dl.as2.dnanex.us/F/D/zZYkV9Y3XPfyVjGJKqQXkKFk98V73q697gGB9kvv/ClinSV_x86_64_v1.0.tar.gz.md5sum
https://dl.as2.dnanex.us/F/D/4ZkYz86X3bQZpbY8XJ29b6404BgqjjqX75172QZz/refdata-b38_v1.0.tar
https://dl.as2.dnanex.us/F/D/1Z7zBkYYVkvg5kq0vFqvqpzBz0BF7BJqgPgz9x1b/refdata-b38_v1.0.tar.md5sum

**Comment by shyamrav** [comment]
Thanks Mark!

**Comment by tstokowy** [comment]
Hi Mark, is there any chance I could get links for hg19 as well? The download still does not work.

Kind regards,

Tomasz Stokowy

**Comment by drmjc** [comment]
no probs - 
https://dl.as2.dnanex.us/F/D/FzZqkB6J2PjjjYB9Q5JZF051PxxygqX8Z3yjBgGP/ClinSV_scripts_only_v0.9.tar.gz
https://dl.as2.dnanex.us/F/D/YYb87GK3593F3xz1P0q6j545b1yyXkjfJj232V3V/ClinSV_scripts_only_v0.9.tar.gz.md5sum
https://dl.as2.dnanex.us/F/D/JyfPqVj75Jy8165vvK84b3B14pzjyxXZxBJkjG4V/ClinSV_x86_64_v0.9.tar.gz
https://dl.as2.dnanex.us/F/D/xfJVy0kY3fVX1KK02JvX3Q2VPkz4zPfY05ZFB1bB/ClinSV_x86_64_v0.9.tar.gz.md5sum
https://dl.as2.dnanex.us/F/D/z82zXkFvB3kbfF7GX1xj4q3vJY8g47947vFYj57g/clinsv.sif
https://dl.as2.dnanex.us/F/D/yxBFpzbYg4zpQj8YkFqf916ZpV5V1XF9p7jVJPVB/refdata-b37_v0.9.tar
https://dl.as2.dnanex.us/F/D/BX0ZK4pyk7pyYzFxpP4qvp4fFGky3vykFyKKpbvX/refdata-b37_v0.9.tar.md5sum

**Comment by drmjc** [comment]
the server is back up and running. thanks for flagging the issue
