### ISSUE TITLE
ClinSV suitable for nanopore data?

### ISSUE THREAD

**Issue by mantonglaw** [KCCG/ClinSV#18]
Hi!
I have some data, 30 × WGS，from nanopore sequcing，could I use ClinSV to call CNV?

**Comment by MinocheAE** [comment]
Hi,

In the SV calling step ClinSV uses Lumpy and CNVnator. For Nanopore data it is better to use a tool such as Sniffles:
https://github.com/fritzsedlazeck/Sniffles <https://github.com/fritzsedlazeck/Sniffles>

However, ClinSV's SV genome browser tracks will be helpful, when visualising candidate variants in a genome browser like IGV.

You could download them from here. See folder the tracks in 

Build 38:
https://nci.space/_projects/clinsv_b38/refdata-b38_v1.0.tar

or 

Build 37:
https://www.nci.space/clinsv/refdata-b37_v0.9.tar <https://www.nci.space/clinsv/refdata-b37_v0.9.tar>


For details on the annotation tracks, please see Figure 1 in the attached document.



Best regards
Andre

**Comment by MinocheAE** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/11867037/148689956-7d3eafec-b515-4776-abe8-629db367ee6e.png">

Figure 1 Default genome browser tracks for manual validation 
This region and tracks are display if the IGV session is loaded correctly. It shows a commonly deleted repeat sequence.

1)	Depth of coverage of control sample NA12878
2)	Depth of coverage of input sample
3)	Depth of coverage of sequence read bases with a Phred scaled mapping quality >=20
4)	Average mapping quality of aligned reads for current sample 
5)	Coverage standard deviation in 1kb windows of 500 healthy individuals (MGRB cohort)
6)	Regions of segmental duplication as determined by Bailey JA et al. 2002 (Seg-Dup, none in this region)
7)	Annotated ClinSV calls from Lumpy and CNVnator
8)	Discordant pairs of input sample, followed by discordant pairs of control sample NA12878 (scroll down)
9)	Split reads of input sample, followed by split reads of control sample NA12878
10)	ClinSV variants from 500 healthy control samples (MGRB cohort) called in batches of 15 samples 
11)	Structural variants deposited in Database of Genomic Variants (DGV); feature name indicates the population allele frequency, study sample size, author and DGV ID.
12)	RefSeq genes 
13)	ENSEMBL genes (used for annotation)

**Comment by mantonglaw** [comment]
Thanks for your thorough answer! I will try it.
