### ISSUE TITLE
GIAB reference file for sensitivity

### ISSUE THREAD

**Issue by wishvaherath** [KCCG/ClinSV#21]
Can you please let me know the location of  `GIAB_SV_DEL_gold_noNonCnvGr500_vPB.bed` file that is used for the sensitivity analysis for GIAB1?

Cheers,
Wishva

**Comment by MinocheAE** [comment]
Hi Wishva,

As I don't have access to this file anymore, I will ask my former colleagues if they can locate it and then report back.

Kind regards,
Andre

**Comment by joecop** [comment]
Hi Wishva 
I have emailed you with the file attached. 
Kind regards
Joe
