### ISSUE TITLE
Unable to download reference data

### ISSUE THREAD

**Issue by melnel000** [KCCG/ClinSV#29]
Hi

I am having an issue when trying to download the reference data. This is the error message I am receiving:

wget https://nci.space/_projects/clinsv_b38/refdata-b38_v1.0.tar
--2022-06-09 20:30:01--  https://nci.space/_projects/clinsv_b38/refdata-b38_v1.0.tar
Resolving nci.space (nci.space)... 130.56.242.205
Connecting to nci.space (nci.space)|130.56.242.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38952581120 (36G) [application/x-tar]
Saving to: ‘refdata-b38_v1.0.tar’

refdata-b38_v1.0.tar                                74%[==================================================================================>                              ]  26.95G  5.50MB/s    in 80m 19s 

Cannot write to ‘refdata-b38_v1.0.tar’ (Success).

I tried a second time and the same thing happened, the download stopped at 64%.

Please can you let me know what might be causing this problem.

Thanks,
Melissa

**Comment by J-Bradlee** [comment]
Hi Melissa,

Just confirming you have at least 37gb worth of space on your machine? The tar file is 37gb.

**Comment by melnel000** [comment]
Yes, I have just checked and I still have 178GB available.

**Comment by J-Bradlee** [comment]
Strange, it should work. I will upload that file to a public bucket and share with you the link when its ready. Is there any other files you are having issues getting?

**Comment by melnel000** [comment]
No, it's just this file that is a problem. Thanks for trying the public bucket option.

**Comment by J-Bradlee** [comment]
@melnel000 try downloading it now from https://storage.googleapis.com/refb38/refdata-b38_v1.0.tar

**Comment by melnel000** [comment]
Thanks, I was able to download the reference data. How long does it take to run the pipeline on a single sample?

**Comment by J-Bradlee** [comment]
depends on the size of the bam/bai files. A 60gb bam file takes around 24 hours, a 5-6gb bam file takes roughly 6 hours.
