### ISSUE TITLE
reference issue

### ISSUE THREAD

**Issue by fjmuzengyiheng** [KCCG/ClinSV#3]
Dear authors,
Thank you for providing this outstanding tool.
Error occurred when I run:

docker run \
-v ${refdata_path}:/app/ref-data \
-v ${project_folder}:/app/project_folder \
-v ${input_path}:/app/input \
kccg/clinsv -r all \
-i "/app/input/*.bam" \
-ref ${refdata_path}:/app/ref-data \
-p ${project_folder}:/app/project_folder

it says:
……
 ### executing: sh /app/project_folder/SVs/joined/lumpy/sh/lumpy.caller.joined.sh &> /app/project_folder/SVs/joined/lumpy/sh/lumpy.caller.joined.e  ...  

 ### finished after (hh:mm:ss): 00:00:10
 ### exist status: 256

 ***** error exist status != 0 (256), **please check /app/project_folder/SVs/joined/lumpy/sh/lumpy.caller.joined.e for more information**

so i check the log and found it was a reference issue:
[main_samview] region "1:1000000-1100000" specifies an unknown reference name. Continue anyway.

I noticed reference file is /refdata-b37/genome/human_g1k_v37_decoy.fasta
But my bam files are mapped using  hg19(with chromosomes named"chr1"...) instead of grch37(with chromosomes named "1"...)

Hou can I fix this? 
Can I simply replace human_g1k_v37_decoy.fasta with hg19.fa(my reference file)?

Thank you again.

Best wishes

**Comment by MinocheAE** [comment]
Hi, thank you for your interest

The required reference is human_g1k_v37_decoy.fasta. 

As work around you could try reformatting your bam by removing "chr" from the names,

or use this version, for which there is no docker yet, and change line 217 of bin/clinsv from $chrPf='chr';  to $chrPf=''; 
https://nci.space/_projects/clinsv_b38/ClinSV_scripts_only_v1.0.tar.gz

**Comment by fjmuzengyiheng** [comment]
> Hi, thank you for your interest
> 
> The required reference is human_g1k_v37_decoy.fasta.
> 
> As work around you could try reformatting your bam by removing "chr" from the names,
> 
> or use this version, for which there is no docker yet, and change line 217 of bin/clinsv from $chrPf='chr'; to $chrPf='';
> https://nci.space/_projects/clinsv_b38/ClinSV_scripts_only_v1.0.tar.gz



I get it. Thank you for replying.    : )
