### ISSUE TITLE
No linked file for gene list

### ISSUE THREAD

**Issue by melnel000** [KCCG/ClinSV#33]
To mark variants affecting user defined candidate genes, a [gene list](https://github.com/KCCG/ClinSV/blob/master/misc/testGene.ids) list has to be placed into the project folder and named "testGene.ids". Gene names have to be as in ENSEMBL GRCh37.

There is no linked file for [gene list]

What is the format of this file? Should dI be using gene symbols or ENSEMBL IDs?

Thanks,
Melissa

**Comment by J-Bradlee** [comment]
As far as I know, the current gene list being used by ClinSV can be found for ref-b37 under annotations (at this path refdata-b37/annotation/Homo_sapiens.GRCh37.75.ids) . It is using gene symbols, running the command `head  refdata-b37/annotation/Homo_sapiens.GRCh37.75.ids` gives me the following output:

```
5S_rRNA
7SK
A1BG
A1BG-AS1
A1CF
A2M
A2M-AS1
A2ML1
A2ML1-AS1
A2ML1-AS2
```

Also your link provided is broken.

Hope this helps.
