### ISSUE TITLE
 Is there any easy way to install clinsv_b38?

### ISSUE THREAD

**Issue by deb0612** [KCCG/ClinSV#4]
Dear sir,
I tried to follow the instruction (https://github.com/KCCG/ClinSV/blob/master/INSTALL_b38.md) to install the ClinSV v1.0.
However I found it was hard to finish. 
Could you provide a easy way to use clinsv like docker or conda?

**Comment by drmjc** [comment]
Dear deb0612,
Thank you for this feedback. You are not alone in finding this a bit difficult, so we are working on getting some resources to solve this. I don't have an immediate timeline at this stage for you though.

**Comment by drmjc** [comment]
Hi,
I've had no luck on getting some students to help on this project, so I'm still not sure when I'll be able to make this improvement.

Thanks

**Comment by drmjc** [comment]
we're working on this now...
