### ISSUE TITLE
nci.space :: download problem

### ISSUE THREAD

**Issue by EricDeveaud** [KCCG/ClinSV#44]
Hello,

one of our user requested the ability to run some analysis on human genome reference data GRCh37 and after reading. 
#27 and #28 I decidedto give a try to version ClinSV-1.1 dev branch ;-)

problem I have is that I can't download https://nci.space/clinsv/refdata-b37_v0.9.tar (nor any other file from this host)

regards

Eric

**Comment by EricDeveaud** [comment]
here is  the wget output.
```
wget  https://nci.space/clinsv/refdata-b37_v0.9.tar
--2023-02-10 17:11:17--  https://nci.space/clinsv/refdata-b37_v0.9.tar
Resolving nci.space (nci.space)... 130.56.242.205
Connecting to nci.space (nci.space)|130.56.242.205|:443... connected.
HTTP request sent, awaiting response... Read error (Success.) in headers.
Retrying.
```

**Comment by drmjc** [comment]
Thanks, I've contacted the domain host. in the meantime:

wget https://clinsv.s3.ccia.org.au/clinsv/refdata-b37_v0.9.tar

the IGV session files will still have URL's to nci.space, so they temporarily won't work.

**Comment by drmjc** [comment]
reopening ticket until the nci.space host is back up and running...

**Comment by drmjc** [comment]
The server is back up. need to change the paths for x38 data though
examples

wget https://nci.space/clinsv/clinsv_b38/refdata-b38_v1.0.tar
wget https://nci.space/clinsv/refdata-b37_v0.9.tar
wget https://nci.space/clinsv/clinsv_b37/refdata-b37_v0.9.tar
