### ISSUE TITLE
Unable to download human genome reference data GRCh38

### ISSUE THREAD

**Issue by sttongjai** [KCCG/ClinSV#54]
Hello,

I have tried downloading human genome reference data GRCh38 from a given link (https://nci.space/clinsv/clinsv_b38/refdata-b38_v1.0.tar), but I could not download the data. There is a problem with host address ‘nci.space’, as shown below.

$ wget https://nci.space/clinsv/clinsv_b38/refdata-b38_v1.0.tar
--2023-03-23 21:25:54--  https://nci.space/clinsv/clinsv_b38/refdata-b38_v1.0.tar
Resolving nci.space (nci.space)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘nci.space’

Could you please check whether the provided link is working?

Thank you very much.

Siripong

**Comment by drmjc** [comment]
Thanks for reporting, I'll look into it

**Comment by MatDaw** [comment]
Hello,

Is there a possibility to temporarily share the file on another file hosting? Or maybe we can use an alternative reference genome?

Thanks,
Mateusz

**Comment by adarsh-pp** [comment]
Hello, 

I am also getting the same error while trying to download the referenence as well as the example data. Please update on this issue. Is it necessary to use this same reference or can we use an alternate file?

Thanks,
Adarsh

**Comment by drmjc** [comment]
Hi, the nci.space domain has expired and the postdoc who bought it left... I need to come up with a permanent solution for this.

**Comment by drmjc** [comment]
migrating data to an s3 bucket...

**Comment by petaleaf** [comment]
> migrating data to an s3 bucket...

thank you

**Comment by adarsh-pp** [comment]
> migrating data to an s3 bucket...

Thank you. Please share about how to access it.

**Comment by tstokowy** [comment]
Hi, it seems the issue persists. I also can not access reference data. Regards, Tomasz

**Comment by SaulGoodman1337** [comment]
same issue. need reference

**Comment by drmjc** [comment]
Hi,
The reference data are now available on s3. These are some of the key files:
https://clinsv.s3.ccia.org.au/clinsv_b38/refdata-b38_v1.0.tar
https://clinsv.s3.ccia.org.au/clinsv_b38/ClinSV_x86_64_v1.0.tar.gz
https://clinsv.s3.ccia.org.au/clinsv_b38/ClinSV_scripts_only_v1.0.tar.gz
https://clinsv.s3.ccia.org.au/clinsv_b38/NA12878_b38.bam
https://clinsv.s3.ccia.org.au/clinsv_b38/NA12878.grch38.subsampled.bam

I still need to update the docs, and the code that creates the IGV manifest files, but this should get you started...

yes hs37d5 data is also available for use with ClinSV v0.9:
https://clinsv.s3.ccia.org.au/clinsv_b37/refdata-b37_v0.9.tar
https://clinsv.s3.ccia.org.au/clinsv_b37/ClinSV_x86_64_v0.9.tar.gz
https://clinsv.s3.ccia.org.au/clinsv_b37/ClinSV_scripts_only_v0.9.tar.gz
https://clinsv.s3.ccia.org.au/clinsv_b37/NA12878_v0.9.bam

**Comment by SaulGoodman1337** [comment]
I just want to say thank you. Runs 👍
