### ISSUE TITLE
Unable to download reference data from s3 bucket

### ISSUE THREAD

**Issue by TonyLupara** [KCCG/ClinSV#56]
Hi there,

I've tried to download reference genomes refdata-b38_v1.0.tar/refdata-b37_v0.9.tar with wget. 

But i can't connect to s3 bucket:
`Connecting to clinsv.s3.ccia.org.au (clinsv.s3.ccia.org.au)|103.144.124.158|:443... failed: Connection timed out.`

**Comment by drmjc** [comment]
There might have been a temporary disruption. Can you please try again?
Thanks

**Comment by TonyLupara** [comment]
Thank you for quick response. I've tried to download, but threre is still no connection to S3 bucket.

**Comment by drmjc** [comment]
what URL are you using? these both work for me?

> wget https://clinsv.s3.ccia.org.au/clinsv_b37/refdata-b37_v0.9.tar
> wget https://clinsv.s3.ccia.org.au/clinsv_b38/refdata-b38_v1.0.tar

**Comment by TonyLupara** [comment]
I've used exactly the same URLs as you provided below. Strange thing)
Maybe i should use different port?

**Comment by drmjc** [comment]
Where are you based? can you try additional servers/computers? In the meantime, i'll ask our IT department if there's some geolock

**Comment by drmjc** [comment]
It's likely the port. Try the same link with s3.ccia.org.au:10443

**Comment by TonyLupara** [comment]
Actually i'm in Moscow, maybe it's really some geolock. Port 10443 also didn't work for me. Sorry)

**Comment by Bioinf-usr** [comment]
Hi,
 
 I am also running into the same issue. I am stuck here for an hour or so. Could you please check?
 
 ```
 wget https://clinsv.s3.ccia.org.au/clinsv_b38/refdata-b38_v1.0.tar
--2024-07-08 14:21:39--  https://clinsv.s3.ccia.org.au/clinsv_b38/refdata-b38_v1.0.tar
Resolving clinsv.s3.ccia.org.au (clinsv.s3.ccia.org.au)... 103.144.124.158
Connecting to clinsv.s3.ccia.org.au (clinsv.s3.ccia.org.au)|103.144.124.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38952581120 (36G) [binary/octet-stream]
Saving to: ‘refdata-b38_v1.0.tar’
 0% [                                                              ] 15,097,438  74.7KB/s  eta 5d 8h
 ```
