### ISSUE TITLE
No Docker image

### ISSUE THREAD

**Issue by HudoGriz** [KCCG/ClinSV#57]
Hello.

I just want to point out that on docker-hub there is no  image `mrbradley2/clinsv:v1.0.1` (as stated in the README).

Thanks for the great work,

Blaž

**Comment by dppss90008** [comment]
Dear Author 

I encounter the same issue.

CH

**Comment by dppss90008** [comment]
![image](https://github.com/KCCG/ClinSV/assets/34399929/80a3d817-e65c-46f6-9c71-68605f9a9f86)

What I can see on the docker hub is version 1.1-dev.

Is it right using this version ?

Thnaks 

CH

**Comment by thedam** [comment]
Still the problem persists

**Comment by J-Bradlee** [comment]
Hi guys, there is no docker version for v1.0.1. I am working on merging v1.0.1 with the current v1.1-dev branch.  

v1.0.1 mainly fixes the XML issues to point to the correct resource files for IGV. I'm working on dockerizing all these changes, in an updated version of the v1.1-dev docker image.
