### ISSUE TITLE
No dots/lines in the coverage by chromosome view (CBCV) 

### ISSUE THREAD

**Issue by Bin-Guan** [KCCG/ClinSV#60]
Hello,
We run version 1.1 on a bam and all steps completed without errors. However, the coverage by chromosome view in the QC_report.pdf showed 24 lines of "## Warning: NAs introduced by coercion" followed by a grid of 1 to 22 without dots or lines. What could be the problem? 

Tested using the supplied bam file NA12878.grch38.subsampled.bam, it showed the same problem. The text file in SVs\qc\chromView\ only had chromosome numbers but no other information: 
chr1 TAB
...
chrXX TAB
chrY0 TAB
chrM TAB

Thank you.

**Comment by Bin-Guan** [comment]
Here is the pdf report, where the other plots were fine except the CBCV. [COL005.1.QC_report.pdf](https://github.com/KCCG/ClinSV/files/14117731/COL005.1.QC_report.pdf)

**Comment by J-Bradlee** [comment]
Hi @Bin-Guan thank you for bringing this up. I get the same results. I think it has something to do with scripts/validReportPrep.pl line 256-264 on the v1.1-dev branch. Working on it!
