### ISSUE TITLE
Is there T2T refdata of ClinSV?

### ISSUE THREAD

**Issue by yougulianren** [KCCG/ClinSV#67]
Hi,
   I have used T2T CHM13v2 as ref genome to alignment, I want to use Clinsv to call SV and CNV right now. Is there corresponding ref-data of ClinSV to use?

**Comment by drmjc** [comment]
Hi, this is a nice suggestion, but as I don't yet use the t2t ref genome in
our group, I don't see this coming to clinsv for 12 or more months.
Cheers
