### ISSUE TITLE
clinSV docker doesn't work

### ISSUE THREAD

**Issue by liqi814** [KCCG/ClinSV#8]
I was using two samples to run the test with their corresponding index files.
```
sudo docker run \
> -v $refdata_path:/app/ref-data \
> -v $project_folder:/app/project_folder \
> -v $input_path:/app/input \
>   kccg/clinsv -r all \
> -i "/app/input/*.bam" \
> -ref $refdata_path:/app/ref-data \
> -p $project_folder:/app/project_folder
##############################################
####                ClinSV                ####
##############################################
# 26/07/2021 20:40:30

# clinsv dir: /app/clinsv
# projectDir: /app/project_folder
# sampleInfoFile: /app/project_folder/sampleInfo.txt
# name stem: project_folder
# lumpyBatchSize: 15
# genome reference: /app/ref-data
# run steps: all
# number input bams: 2

# Create sample info file from bam files ...
ln -s  /app/project_folder/alignments//.bam
```

Here is the output directory. I didn't get anything and the _sampleInfo.txt_ is empty.

```
lh test_run/*
-rw-r--r--. 1 root root    0 Jul 26 16:40 test_run/sampleInfo.txt

test_run/alignments:
total 12K
drwxr-xr-x. 3 root   root          4.0K Jul 26 16:40 .
drwxr-xr-x. 3 root   root          4.0K Jul 26 16:40 ..
drwxr-xr-x. 2 root   root          4.0K Jul 26 16:40 sh
```

**Comment by baranaldemir** [comment]
Same problem. Have you find any solution ?

**Comment by IshakYusuf** [comment]
Dear Kccg
I run the command on docker and UNIX and I have the same result. Any suggestion, please? 
The command

`docker run -v $refdata_path:/app/ref-data -v $project_folder:/app/project_folder -v $input_path:/app/input  kccg/clinsv  -i /app/input/*.bam -ref $refdata_path:/app/ref-data -p $project_folder:/app/project_folder
`
The result 
 
`##############################################
####                ClinSV                ####
##############################################
# 29/07/2021 07:44:33

# clinsv dir: /app/clinsv
# projectDir: /app/project_folder
# sampleInfoFile: /app/project_folder/sampleInfo.txt 
# name stem: project_folder
# lumpyBatchSize: 15
# genome reference: /app/ref-data
# run steps: all
# number input bams: 2

# Read Sample Info from /app/project_folder/sampleInfo.txt
# 0 samples to process
# If not, please exit make a copy of sampleInfo.txt, modify it and rerun with -s sampleInfo_mod.txt pointing to the new sample info file. 

###### Generate the commands and scripts ######

# bigwig

# lumpy

# cnvnator

# annotate

# prioritize

# qc

###### Run jobs ######

# 29/07/2021 07:44:33 Project project_folder project_folder | Total jobs 0 | Remaining jobs 0 | Remaining steps   0 | Total time: 0 min

# Everything done! Exit

# writing igv session files...
`

**Comment by liqi814** [comment]
Hey Guys try to manually put your sampleIDs in the sampleInfo.txt

**Comment by IshakYusuf** [comment]
> Hey Guys try to manually put your sampleIDs in the sampleInfo.txt

Does this file  output or input?

**Comment by MinocheAE** [comment]
Hi

"sampleInfo.txt" is created automatically from the bam file header, but only if there is no such file in the output directory. If such file exists, the sample information is read from it.

Running ClinSV on the the sample bam https://nci.space/clinsv/NA12878_v0.9.bam may help to debug.

From liqi814 initial post I believe the sample name could not be read from the bam header. Compare your bam header with the one of NA12878_v0.9.bam, and try to adjust it accordingly.

Creating a sampleInfo.txt file manully may be a workaround. It is created from these bam readgroup tags and the bam file path:
SM{TAB}ID{TAB}LB{TAB}bamFilePath
One line per bam

Also if you use the wildcard * for the bams, better put it in quotes as in the example in "https://github.com/KCCG/ClinSV". The wildcard needs to be interpreted from within the container. 

I hope this helps :-)

**Comment by IshakYusuf** [comment]
> Hi
> 
> "sampleInfo.txt" is created automatically from the bam file header, but only if there is no such file in the output directory. If such file exists, the sample information is read from it.
> 
> Running ClinSV on the the sample bam https://nci.space/clinsv/NA12878_v0.9.bam may help to debug.
> 
> From liqi814 initial post I believe the sample name could not be read from the bam header. Compare your bam header with the one of NA12878_v0.9.bam, and try to adjust it accordingly.
> 
> Creating a sampleInfo.txt file manully may be a workaround. It is created from these bam readgroup tags and the bam file path:
> SM{TAB}ID{TAB}LB{TAB}bamFilePath
> One line per bam
> 
> Also if you use the wildcard * for the bams, better put it in quotes as in the example in "https://github.com/KCCG/ClinSV". The wildcard needs to be interpreted from within the container.
> 
> I hope this helps :-)

Thanks for your response. It works perfectly. I have other a question please
where can I get reference genome hg38?

**Comment by MinocheAE** [comment]
This is the reference data directory for b38, however there is no docker for it.
https://nci.space/_projects/clinsv_b38/refdata-b38_v1.0.tar

You would need to install the dependencies as describe here:
https://github.com/KCCG/ClinSV/blob/master/INSTALL_b38.md

see:
https://github.com/KCCG/ClinSV#build-38

**Comment by IshakYusuf** [comment]
Thanks for explaining.
Could you explain this line 
 **SM**{TAB}**ID**{TAB}**LB**{TAB}bamFilePath
I do not get how to figure out SM ID LB ?

**Comment by IshakYusuf** [comment]
Dear MinocheAE

Thank you so much 

I run the software and I get this message.

`lumpy variants not present: /home/gnks/Desktop/Temp_yusuf_baran/ClinSV_38/project_folder/SVs/joined/SV-CNV.MeHaGor.igv.bed.gz
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl/5.26/File/Basename.pm line 180.
/home/gnks/Desktop/Temp_yusuf_baran/ClinSV_38/project_folder/SVs/qc/sh/qc.main.joined.sh: 1: set: Illegal option -o pipefail
fileparse(): need a valid pathname at /home/gnks/Desktop/Temp_yusuf_baran/ClinSV_38/clinsv/bin/clinsv line 1002.`

shall I reinstall lumpy again?
